"""m2c model_usage_daily 记账表

Revision ID: 0162e47a6dcf
Revises: 7af213d6752c
Create Date: 2026-08-21 18:29:03.769065

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0162e47a6dcf"
down_revision: str | None = "7af213d6752c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_usage_daily",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), nullable=False),
        sa.Column("total_tokens", sa.BigInteger(), nullable=False),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["model_providers.id"],
            name=op.f("fk_model_usage_daily_provider_id_model_providers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_usage_daily")),
        sa.UniqueConstraint("provider_id", "date", name=op.f("uq_model_usage_daily_provider_id")),
    )
    op.create_index(
        op.f("ix_model_usage_daily_provider_id"), "model_usage_daily", ["provider_id"], unique=False
    )
    # 原先此处是 autogenerate 生成的 checkpoint_* 四表 DROP（当时这些表未纳入 metadata）。
    # 它们由 LangGraph checkpointer 运行期自建、不归 alembic 管，且空库首次建表时并不存在，
    # 保留会让整条迁移链在空库上以 UndefinedTableError 中断。过滤见 migrations/env.py 的 include_name。
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_usage_daily_provider_id"), table_name="model_usage_daily")
    op.drop_table("model_usage_daily")
    # ### end Alembic commands ###
